### ISSUE TITLE
Problem with ejs

### ISSUE THREAD

**Issue by RajatSablok** [RajatSablok/free-slot-finder#15]
I am getting the following error while rendering the ejs template

![Screenshot (23)](https://user-images.githubusercontent.com/48065690/62851032-6a267400-bd02-11e9-95ae-d129c2d22e12.png)

**Comment by RishabhKodes** [comment]
This is some syntax error. I don't think there's any problem with the server side code.

**Comment by L04DB4L4NC3R** [comment]
Yeah there is a problem with your ejs template.

**Comment by RajatSablok** [comment]
![Screenshot (25)](https://user-images.githubusercontent.com/48065690/62863043-517b8580-bd25-11e9-864a-84a79dc6fae9.png)
 Problem while deploying

**Comment by RishabhKodes** [comment]
Problem is in the line 58 of app.js, the **filename is not defined**. Replace it with the name of the file which has the html or bootstrap code.

**Comment by L04DB4L4NC3R** [comment]
> Problem is in the line 58 of app.js, the **filename is not defined**. Replace it with the name of the file which has the html or bootstrap code.

The error was due to the fact that there was no uploads folder in public/ during runtime. It has been solved. This issue can be closed now @RajatSablok
