### ISSUE TITLE
Problem with ejs

### ISSUE THREAD

**Issue by RajatSablok** [RajatSablok/free-slot-finder#3]
I want to be able to display the contents of a text file on the web page. 
I have used EJS as the template engine for displaying the contents of that text file. But since the content is stored in a variable, I can't understand how to display it on the page.

app.js is the entry point of the project and it is in the root directory. 
The EJS file is in the 'views' directory by the name upload.ejs
The text file to be read and displayed is in public folder
The first screenshot shows index.html file
The second screenshot shows upload.ejs file and the markings show where the content from the text file has to be shown.

Can someone help me with it?

![1](https://user-images.githubusercontent.com/48065690/62416929-51162700-b661-11e9-9eb1-5de2e8469eb2.png)

![2](https://user-images.githubusercontent.com/48065690/62416930-52dfea80-b661-11e9-9be9-394227f57f9e.jpg)

**Comment by subhrapaladhi** [comment]
Data can be sent from the app.js file to the upload.ejs file when you render it using objects. 
For example your data is stored in the variable 'uploaddata' in your app.js file. While rendering the ejs file do this the send the variable : res.render('upload.ejs', {'data' : uploaddata})

**Comment by subhrapaladhi** [comment]
There is some syntax error in the code that you wrote in upload.ejs file.

`<%= fs.readFile("./public/temp.txt", "utf-8", (err, data) => { 
    if (err) throw err;
     console.log(data); 
     
   }) %>`
This part should be like this
`<% fs.readFile("./public/temp.txt", "utf-8", (err, data) => { %>
   <% if (err) {%>
          <% console.log(err) %>
   <% } else {%>
          <% console.log(data); %>
           < p id="demo" > <%= data%></p>
   <% }) %>`

**Comment by RajatSablok** [comment]
I am still getting this error

![Screenshot (14)](https://user-images.githubusercontent.com/48065690/62420736-00c8b480-b6b5-11e9-92cc-6e7e588e6ec2.png)

**Comment by RajatSablok** [comment]
> I am still getting this error
> 
> ![Screenshot (14)](https://user-images.githubusercontent.com/48065690/62420736-00c8b480-b6b5-11e9-92cc-6e7e588e6ec2.png)

Solved this by adding "}" but still can't display the contents

**Comment by L04DB4L4NC3R** [comment]
Don't read the file in the template. Read the file in the backend and then pass the variable directly into the template

**Comment by YashMeh** [comment]
A quick fix would be to use 'fs.readsync'(blocking operation) before rendering the page and then sending the variable to the page instead of the whole filesystem...
 *fs.readFileSync'

**Comment by L04DB4L4NC3R** [comment]
@YashMeh I'm not sure filesystem can be accessed while rendering a template. Are you sure?

**Comment by YashMeh** [comment]
@L04DB4L4NC3R it won't happen while the template is rendered, it will block the process and once it gets finished then the template will be rendered I guess.

**Comment by L04DB4L4NC3R** [comment]
The best way is to pass a variable by reading the file in the backend itself. Because in future if we decide that we don't want to create an intermediate txt file and just pipe the output directly to a template then we'll have to change the entire function inside the template itself

**Comment by YashMeh** [comment]
Reading of the file will be done in the backend itself,only the content of the file will be passed as a variable in the template.But all this needs to be done synchronously, that is what I was proposing.

**Comment by YashMeh** [comment]
@RajatSablok I think your issue got resolved,kindly close it.
